all: pingpong-task1 pingpong-task2 pingpong-task3

pingpong-task1: pingpong.c pingpong-tasks1.c datatypes.h pingpong.h
	gcc -Wall -o pingpong-task1 pingpong.c pingpong-tasks1.c -I.

pingpong-task2: pingpong.c pingpong-tasks2.c datatypes.h pingpong.h
	gcc -Wall -o pingpong-task2 pingpong.c pingpong-tasks2.c -I.

pingpong-task3: pingpong.c pingpong-tasks3.c datatypes.h pingpong.h
	gcc -Wall -o pingpong-task3 pingpong.c pingpong-tasks3.c -I.
