all:
	gcc -Wall -o pingpong-contab-prio pingpong.c pingpong-contab-prio.c queue.c -I.
	gcc -Wall -o pingpong-contab pingpong.c pingpong-contab.c queue.c -I.
	./pingpong-contab-prio	
	./pingpong-contab